const errorDatabase = [
    {
        codigo: "2002-4364",
        programa: "010000000000000C",
        titulo: "Crash de Atmosphere durante el arranque",
        titulo_en: "Atmosphere crash during boot",
        titulo_pt: "Crash do Atmosphere durante a inicialização",
        alias: ["pantallazo al encender", "atmosphere no arranca", "error en el logo"],
        causas: ["Temas personalizados incompatibles con la nueva versión", "microSD en exFAT corrupta", "Datos de guardado corruptos"],
        causas_en: ["Custom themes incompatible with new version", "Corrupted exFAT microSD", "Corrupted save data"],
        causas_pt: ["Temas personalizados incompatíveis com a nova versão", "microSD exFAT corrompido", "Dados de save corrompidos"],
        solucion: "1. Si actualizaste recientemente, conecta la SD al PC, ve a 'atmosphere/contents' y borra la carpeta '0100000000001000' (Temas).\\n2. Comprueba si tu SD tiene errores (preferible usar FAT32).\\n3. Recrea la emuMMC si el fallo persiste.",
        solucion_en: "1. If you updated recently, connect SD to PC, go to 'atmosphere/contents' and delete '0100000000001000' folder (Themes).\\n2. Check SD card for errors (FAT32 recommended).\\n3. Recreate emuMMC if the issue persists.",
        solucion_pt: "1. Se atualizou recentemente, conecte o SD no PC, vá para 'atmosphere/contents' e apague a pasta '0100000000001000' (Temas).\\n2. Verifique erros no SD (recomendado FAT32).\\n3. Recrie a emuMMC se o erro persistir.",
        fuente: "Reddit / Comunidad"
    },
    {
        codigo: "2002-1002",
        programa: "Varios (al iniciar juegos)",
        titulo: "Error de Tarjeta SD / Datos Corruptos en Juegos",
        titulo_en: "SD Card Error / Corrupted Game Data",
        titulo_pt: "Erro no Cartão SD / Dados Corrompidos no Jogo",
        alias: ["juego no abre", "datos dañados", "no me instalan los nsp"],
        causas: ["Partición de la emuNAND corrupta", "Juego mal instalado o archivos dañados", "Tarjeta microSD genérica/falsa o formateada en exFAT"],
        causas_en: ["Corrupted emuNAND partition", "Bad game installation or corrupted files", "Fake microSD or formatted in exFAT"],
        causas_pt: ["Partição da emuNAND corrompida", "Jogo mal instalado ou arquivos danificados", "MicroSD falso ou formatado em exFAT"],
        solucion: "1. Ve a Configuración -> Gestión de datos -> Programas, selecciona el juego y 'Comprobar si hay datos dañados'.\\n2. Si ocurre al instalar juegos nuevos, formatea la SD a FAT32 o comprueba si es falsa (H2testw).\\n3. Borra el juego y vuélvelo a instalar desde cero (DBI).",
        solucion_en: "1. Go to Settings -> Data Management -> Software, select the game and 'Check for Corrupt Data'.\\n2. If it happens installing new games, format SD to FAT32 or check if it's fake (H2testw).\\n3. Delete the game and reinstall it from scratch (DBI).",
        solucion_pt: "1. Vá em Configurações -> Gerenciamento de Dados -> Softwares, selecione o jogo e 'Verificar dados corrompidos'.\\n2. Se acontecer ao instalar novos jogos, formate o SD em FAT32 ou verifique se é falso (H2testw).\\n3. Apague o jogo e instale do zero (DBI).",
        fuente: "GBATemp / Reddit"
    },
    {
        codigo: "std::abort() (0xffe)",
        programa: "010000000000bd00",
        titulo: "Módulo Mission Control Obsoleto",
        titulo_en: "Outdated Mission Control Sysmodule",
        titulo_pt: "Módulo Mission Control Desatualizado",
        alias: ["fatal error occurred", "mando bluetooth", "crash al iniciar"],
        causas: ["El módulo Bluetooth (Mission Control) está desactualizado al subir la Switch a un nuevo firmware masivo."],
        causas_en: ["The Bluetooth module (Mission Control) is outdated after updating the Switch to a major new firmware."],
        causas_pt: ["O módulo Bluetooth (Mission Control) está desatualizado após atualizar o Switch para um novo firmware."],
        solucion: "Ve a la carpeta 'atmosphere/contents/' en tu tarjeta SD y borra la carpeta '010000000000bd00'. Luego, descarga la última versión de Mission Control si quieres seguir usándolo.",
        solucion_en: "Go to the 'atmosphere/contents/' folder on your SD card and delete the '010000000000bd00' folder. Then, download the latest version of Mission Control if you want to keep using it.",
        solucion_pt: "Vá para a pasta 'atmosphere/contents/' no seu cartão SD e apague a pasta '010000000000bd00'. Depois, baixe a versão mais recente do Mission Control.",
        fuente: "GitHub Issues (Atmosphère)"
    },
    {
        codigo: "2144-0001 (0x290)",
        programa: "Homebrew Menu / Álbum",
        titulo: "Falta de Memoria en Applet Mode",
        titulo_en: "Out of Memory in Applet Mode",
        titulo_pt: "Falta de Memória no Modo Applet",
        alias: ["error en el album", "homebrew crashea", "2168-0002"],
        causas: ["Intento de ejecutar homebrew pesado desde el modo Álbum (Applet Mode) en lugar de usar Title Redirect."],
        causas_en: ["Attempting to run heavy homebrew from the Album (Applet Mode) instead of using Title Redirect."],
        causas_pt: ["Tentativa de rodar homebrew pesado pelo Álbum (Applet Mode) em vez de usar Title Redirect."],
        solucion: "No abras el Álbum directamente. En su lugar, mantén presionado el botón 'R' del mando derecho mientras inicias cualquier juego que tengas instalado en la consola. Esto abrirá el Homebrew Menu con acceso a toda la RAM.",
        solucion_en: "Do not open the Album directly. Instead, hold the 'R' button on the right joy-con while launching any installed game. This will open the Homebrew Menu with full RAM access.",
        solucion_pt: "Não abra o Álbum diretamente. Em vez disso, segure o botão 'R' enquanto inicia qualquer jogo instalado. Isso abrirá o Homebrew Menu com acesso total à RAM.",
        fuente: "GBATemp & Reddit"
    },
    {
        codigo: "2002-3005",
        programa: "Boot / Arranque",
        titulo: "PRODINFO corrupto o Downgrade incorrecto",
        titulo_en: "Corrupted PRODINFO or bad Downgrade",
        titulo_pt: "PRODINFO corrompido ou Downgrade incorreto",
        alias: ["no pasa de hekate", "emunand rota"],
        causas: ["Degradación (downgrade) de firmware incorrecta o corrupción en los archivos del sistema PRODINFO de la emuNAND."],
        causas_en: ["Incorrect firmware downgrade or corruption in the emuNAND PRODINFO system files."],
        causas_pt: ["Downgrade de firmware incorreto ou corrupção nos arquivos PRODINFO da emuNAND."],
        solucion: "Debes reconstruir la emuMMC desde cero o restaurar una copia limpia de la NAND que tuvieras guardada previamente mediante Hekate.",
        solucion_en: "You must rebuild the emuMMC from scratch or restore a clean NAND backup that you previously saved via Hekate.",
        solucion_pt: "Você deve reconstruir a emuMMC do zero ou restaurar um backup limpo da NAND feito pelo Hekate.",
        fuente: "GBATemp"
    },
    {
        codigo: "Error Genérico",
        programa: "0100000000000025",
        titulo: "Restos Antiguos en Kernel/Boot",
        titulo_en: "Old leftovers in Kernel/Boot",
        titulo_pt: "Restos antigos no Kernel/Boot",
        alias: ["pantalla negra despues de payload", "no carga atmosphere"],
        causas: ["Incompatibilidad crítica del gestor de arranque al arrancar emuMMC debido a restos de archivos antiguos."],
        causas_en: ["Critical bootloader incompatibility when booting emuMMC due to leftover old files."],
        causas_pt: ["Incompatibilidade crítica do bootloader ao iniciar a emuMMC devido a restos de arquivos antigos."],
        solucion: "Realiza una instalación completamente limpia: borra las carpetas 'atmosphere' y 'bootloader' de tu SD y pon las versiones más recientes. (No sobreescribas, borra primero).",
        solucion_en: "Perform a completely clean installation: delete the 'atmosphere' and 'bootloader' folders from your SD and place the latest versions. (Do not overwrite, delete first).",
        solucion_pt: "Faça uma instalação totalmente limpa: apague as pastas 'atmosphere' e 'bootloader' do seu SD e coloque as versões mais recentes. (Não substitua, apague primeiro).",
        fuente: "GBATemp"
    },
    {
        codigo: "Pantalla Negra",
        programa: "Sysnand / Emunand",
        titulo: "Conflicto KIP / Lector SD",
        titulo_en: "KIP Conflict / SD Reader",
        titulo_pt: "Conflito KIP / Leitor SD",
        alias: ["no enciende", "se queda negro tras el logo", "no arranca"],
        causas: ["Conflicto con módulos KIP obsoletos (como el viejo fs_mitm.kip) o corrupción del lector de tarjetas SD de la consola."],
        causas_en: ["Conflict with obsolete KIP modules (like the old fs_mitm.kip) or console SD card reader hardware failure."],
        causas_pt: ["Conflito com módulos KIP obsoletos (como o antigo fs_mitm.kip) ou falha no leitor de cartão SD."],
        solucion: "Revisa y limpia la carpeta 'atmosphere/kips/'. Si está vacía, prueba la estabilidad con otra tarjeta MicroSD formateada en FAT32 para descartar fallo de hardware del lector.",
        solucion_en: "Check and clean the 'atmosphere/kips/' folder. If it is empty, test stability with another MicroSD formatted in FAT32 to rule out reader hardware failure.",
        solucion_pt: "Verifique e limpe a pasta 'atmosphere/kips/'. Se estiver vazia, teste com outro MicroSD formatado em FAT32 para descartar falha de hardware do leitor.",
        fuente: "ElOtroLado & Reddit"
    },
    {
        codigo: "Error de lectura",
        programa: "010041544D530000",
        titulo: "Rutas incorrectas en emummc.ini",
        titulo_en: "Incorrect paths in emummc.ini",
        titulo_pt: "Caminhos incorretos no emummc.ini",
        alias: ["path config error", "no detecta la emunand"],
        causas: ["Error de sintaxis en las rutas del archivo de configuración de la emuMMC (uso de barras invertidas \\\\ en vez de /)."],
        causas_en: ["Syntax error in the emuMMC config file paths (using backslashes \\\\ instead of /)."],
        causas_pt: ["Erro de sintaxe nos caminhos do arquivo de configuração da emuMMC (uso de barras invertidas \\\\ em vez de /)."],
        solucion: "Abre el archivo 'emummc/emummc.ini' con un bloc de notas y corrige la ruta para que use barras normales (ejemplo: /emummc/Nintendo_emu en lugar de \\emummc\\Nintendo_emu).",
        solucion_en: "Open the 'emummc/emummc.ini' file with a text editor and correct the path to use forward slashes (e.g., /emummc/Nintendo_emu instead of \\emummc\\Nintendo_emu).",
        solucion_pt: "Abra o arquivo 'emummc/emummc.ini' em um bloco de notas e corrija o caminho para usar barras normais (exemplo: /emummc/Nintendo_emu em vez de \\emummc\\Nintendo_emu).",
        fuente: "GitHub Issues (Atmosphère)"
    },
    {
        codigo: "2124-4007 / 2124-4508",
        programa: "Nintendo Network",
        titulo: "Consola Baneada por Nintendo",
        titulo_en: "Console Banned by Nintendo",
        titulo_pt: "Console Banido pela Nintendo",
        alias: ["baneo", "ban", "online no va", "servicios restringidos"],
        causas: ["Nintendo ha detectado telemetría modificada o juegos piratas instalados en la sysNAND y ha bloqueado el certificado de la consola."],
        causas_en: ["Nintendo detected modified telemetry or pirated games installed on sysNAND and banned the console certificate."],
        causas_pt: ["A Nintendo detectou telemetria modificada ou jogos piratas instalados na sysNAND e baniu o certificado do console."],
        solucion: "El baneo de hardware es permanente. No podrás usar los servicios oficiales de Nintendo online (eShop, juego online oficial) en esta consola nunca más. Solo podrás usar Tinfoil o LAN play.",
        solucion_en: "Hardware ban is permanent. You will never be able to use official Nintendo online services (eShop, official online play) on this console again. You can only use Tinfoil or LAN play.",
        solucion_pt: "O banimento de hardware é permanente. Você nunca mais poderá usar serviços online oficiais (eShop, jogo online oficial) neste console. Apenas Tinfoil ou LAN play.",
        fuente: "Nintendo Support"
    },
    {
        codigo: "2155-8007",
        programa: "DNS MITM / Network",
        titulo: "Error de conexión a servidores Nintendo (Bloqueado)",
        titulo_en: "Nintendo servers connection error (Blocked)",
        titulo_pt: "Erro de conexão aos servidores da Nintendo (Bloqueado)",
        alias: ["no conecta al servidor", "error de red", "exosphere", "90dns"],
        causas: ["Estás bloqueando la telemetría de Nintendo con DNS MITM o Exosphere y un juego o servicio oficial intenta conectarse a los servidores."],
        causas_en: ["You are blocking Nintendo telemetry with DNS MITM or Exosphere and an official game or service is trying to connect to the servers."],
        causas_pt: ["Você está bloqueando a telemetria da Nintendo com DNS MITM ou Exosphere e um jogo/serviço oficial tenta se conectar."],
        solucion: "¡Esto es bueno! Significa que tus protecciones anti-baneo están funcionando. Si quieres jugar online a juegos legítimos, debes arrancar en sysNAND limpia (Stock) sin protecciones.",
        solucion_en: "This is a good thing! It means your anti-ban protections are working. If you want to play legitimate games online, you must boot into clean sysNAND (Stock) without protections.",
        solucion_pt: "Isso é bom! Significa que suas proteções anti-ban estão funcionando. Se quiser jogar online jogos legítimos, deve iniciar na sysNAND limpa (Stock) sem proteções.",
        fuente: "GBATemp"
    },
    {
        codigo: "2162-0002",
        programa: "Varios Sysmodules (010000000000002B, etc.)",
        titulo: "Crasheo fatal en segundo plano",
        titulo_en: "Fatal background crash",
        titulo_pt: "Crash fatal em segundo plano",
        alias: ["crasheo de tesla", "sysdvr error", "fatal error atmosphere"],
        causas: ["Tienes un módulo (sysmodule) como Tesla Menu, SaltyNX, SysDVR, o EdiZon en segundo plano que es incompatible con la versión actual de Atmosphère."],
        causas_en: ["You have a background sysmodule like Tesla Menu, SaltyNX, SysDVR, or EdiZon that is incompatible with the current Atmosphere version."],
        causas_pt: ["Você tem um sysmodule em segundo plano como Tesla Menu, SaltyNX, SysDVR ou EdiZon incompatível com a versão atual do Atmosphère."],
        solucion: "Ve a la tarjeta SD en la ruta 'atmosphere/contents/' y busca la carpeta que coincida con el ID del programa que te da el error (ej: 010000000000002B) y bórrala.",
        solucion_en: "Go to your SD card 'atmosphere/contents/' path, find the folder matching the failing Program ID (e.g. 010000000000002B) and delete it.",
        solucion_pt: "Vá ao cartão SD na pasta 'atmosphere/contents/', encontre a pasta correspondente ao ID do Programa do erro (ex: 010000000000002B) e apague.",
        fuente: "Reddit (r/SwitchPirates)"
    },
    {
        codigo: "2123-1502",
        programa: "Tinfoil / Instalador",
        titulo: "Error de Sigpatches / Comunicación",
        titulo_en: "Sigpatches / Communication Error",
        titulo_pt: "Erro de Sigpatches / Comunicação",
        alias: ["tinfoil error", "no descarga", "falla la instalacion"],
        causas: ["Normalmente ocurre al intentar instalar actualizaciones o juegos sin tener los parches de firma (sigpatches) actualizados, o por inestabilidad de la red."],
        causas_en: ["Usually occurs when trying to install updates or games without updated signature patches (sigpatches), or due to network instability."],
        causas_pt: ["Geralmente ocorre ao tentar instalar jogos ou atualizações sem ter os patches de assinatura (sigpatches) atualizados, ou por instabilidade de rede."],
        solucion: "Asegúrate de instalar los últimos sigpatches correspondientes a tu versión de Atmosphère. Si el problema persiste, cambia las DNS de tu red Wi-Fi a las de Google (8.8.8.8).",
        solucion_en: "Make sure you install the latest sigpatches matching your Atmosphere version. If the problem persists, change your Wi-Fi DNS to Google's (8.8.8.8).",
        solucion_pt: "Certifique-se de instalar os últimos sigpatches correspondentes à sua versão do Atmosphère. Se persistir, mude os DNS do seu Wi-Fi para os do Google (8.8.8.8).",
        fuente: "ElOtroLado"
    },
    {
        codigo: "2168-0001",
        programa: "0100000000001000 (Home Menu)",
        titulo: "Corrupción del Menú (exFAT)",
        titulo_en: "Home Menu Corruption (exFAT)",
        titulo_pt: "Corrupção do Menu Principal (exFAT)",
        alias: ["crash al salir del juego", "error al ir al home"],
        causas: ["Generalmente provocado por el controlador exFAT de Nintendo corrompiendo los archivos de temas de Atmosphère o archivos del sistema al salir de aplicaciones pesadas."],
        causas_en: ["Usually caused by Nintendo's exFAT driver corrupting Atmosphere theme files or system files when exiting heavy applications."],
        causas_pt: ["Geralmente causado pelo driver exFAT da Nintendo corrompendo os arquivos de tema do Atmosphère ou arquivos do sistema ao sair de aplicativos pesados."],
        solucion: "Si tienes un tema personalizado, bórralo (carpeta '0100000000001000' en contents). Para una solución definitiva, copia tus archivos al PC y formatea la microSD en FAT32.",
        solucion_en: "If you have a custom theme, delete it ('0100000000001000' folder in contents). For a permanent fix, copy files to PC and format microSD to FAT32.",
        solucion_pt: "Se tiver um tema personalizado, apague-o (pasta '0100000000001000' em contents). Para correção definitiva, copie os arquivos para o PC e formate o microSD em FAT32.",
        fuente: "GitHub Issues"
    },
    {
        codigo: "2016-0601",
        programa: "Gestión de Datos",
        titulo: "Fallo de Lectura de la MicroSD",
        titulo_en: "MicroSD Read Failure",
        titulo_pt: "Falha de Leitura do MicroSD",
        alias: ["sd card read error", "no lee la tarjeta"],
        causas: ["La tarjeta SD está defectuosa físicamente, es falsa (capacidad inflada), o la ranura (lector de tarjetas de la consola) tiene suciedad/está roto."],
        causas_en: ["SD card is physically defective, fake (spoofed capacity), or the console's SD card reader slot is dirty/broken."],
        causas_pt: ["O cartão SD está fisicamente defeituoso, é falso (capacidade adulterada), ou o leitor de cartão do console está sujo/quebrado."],
        solucion: "1. Prueba la SD en tu ordenador con un software como H2testw para verificar si es falsa.\\n2. Si la SD está bien, puede que el lector flex de la Switch esté fallando y necesite reemplazo físico.",
        solucion_en: "1. Test the SD on your PC using software like H2testw to check if it's fake.\\n2. If the SD is fine, the Switch flex reader might be failing and needs physical replacement.",
        solucion_pt: "1. Teste o SD no seu PC com um software como H2testw para verificar se é falso.\\n2. Se o SD estiver bom, o leitor flex do Switch pode estar falhando e requer substituição física.",
        fuente: "Reddit"
    },
    {
        codigo: "2101-0001",
        programa: "Hardware (Carga)",
        titulo: "Cortocircuito en el chip M92T36",
        titulo_en: "Short circuit in M92T36 chip",
        titulo_pt: "Curto-circuito no chip M92T36",
        alias: ["no enciende la pantalla", "solo modo RCM pero no carga", "M92T36"],
        causas: ["Esto no es un error de software. Es un fallo de hardware muy común: el chip de control de carga USB-C (M92T36) o el chip de vídeo (P13USB) se han quemado."],
        causas_en: ["This is not a software error. It is a very common hardware failure: the USB-C charge control chip (M92T36) or the video chip (P13USB) has burned out."],
        causas_pt: ["Não é um erro de software. É uma falha de hardware comum: o chip de controle de carga USB-C (M92T36) ou o chip de vídeo (P13USB) queimou."],
        solucion: "Lamentablemente la única solución es enviar la consola a un técnico especializado en microsoldadura para que reemplace el chip quemado de la placa base.",
        solucion_en: "Unfortunately, the only solution is to send the console to a microsoldering technician to replace the burned chip on the motherboard.",
        solucion_pt: "Infelizmente, a única solução é enviar o console para um técnico de microssoldagem para substituir o chip queimado na placa-mãe.",
        fuente: "GBATemp (Hardware subforum)"
    },
    {
        codigo: "2005-0003",
        programa: "Instalador NSP/XCI",
        titulo: "Archivo NSP o Tarjeta SD Corruptos",
        titulo_en: "Corrupted NSP File or SD Card",
        titulo_pt: "Arquivo NSP ou Cartão SD Corrompidos",
        alias: ["error instalando juego", "dbi error", "falla al instalar nsp"],
        causas: ["El archivo del juego (.nsp/.xci) está incompleto, o estás instalando un juego superior a 4GB en una tarjeta corrupta."],
        causas_en: ["The game file (.nsp/.xci) is incomplete, or you are installing a game larger than 4GB on a corrupted card."],
        causas_pt: ["O arquivo do jogo (.nsp/.xci) está incompleto ou você está instalando um jogo maior que 4GB em um cartão corrompido."],
        solucion: "Vuelve a descargar el archivo del juego desde otra fuente de confianza e instálalo preferiblemente mediante cable USB con DBI (Modo MTP) en lugar de instalarlo copiando a la SD.",
        solucion_en: "Re-download the game file from a trusted source and install it preferably via USB cable using DBI (MTP Mode) instead of copying it to the SD.",
        solucion_pt: "Baixe novamente o arquivo do jogo de uma fonte confiável e instale-o preferencialmente via cabo USB usando DBI (Modo MTP) em vez de copiá-lo para o SD.",
        fuente: "Comunidad Scene"
    },
    {
        codigo: "Failed to parse package3",
        programa: "Bootloader / Hekate",
        titulo: "Error al cargar package3 (Atmosphère)",
        titulo_en: "Error loading package3 (Atmosphere)",
        titulo_pt: "Erro ao carregar package3 (Atmosphère)",
        alias: ["error package_3", "package3", "package 3", "no arranca atmosphere"],
        causas: ["Archivos de Atmosphère desactualizados o faltantes para el firmware actual de la consola.", "Has actualizado Hekate pero se te olvidó actualizar los archivos de Atmosphère en tu tarjeta SD."],
        causas_en: ["Outdated or missing Atmosphere files for the current console firmware.", "You updated Hekate but forgot to update the Atmosphere files on your SD card."],
        causas_pt: ["Arquivos do Atmosphère desatualizados ou ausentes para o firmware atual do console.", "Você atualizou o Hekate, mas esqueceu de atualizar os arquivos do Atmosphère no SD."],
        solucion: "Debes actualizar Atmosphère. Descarga la última versión oficial (el archivo .zip 'release'), extrae su contenido y cópialo a la raíz de tu tarjeta SD, reemplazando la carpeta 'atmosphere' anterior.",
        solucion_en: "You must update Atmosphere. Download the latest official release .zip, extract it, and copy it to the root of your SD card, replacing the old 'atmosphere' folder.",
        solucion_pt: "Você deve atualizar o Atmosphère. Baixe a versão oficial mais recente (.zip release), extraia e copie para a raiz do seu SD, substituindo a pasta 'atmosphere'.",
        fuente: "GBATemp / Reddit"
    },
    {
        codigo: "Warmboot Error",
        programa: "Sleep Mode (Modo Espera)",
        titulo: "Error de Warmboot",
        titulo_en: "Warmboot Error",
        titulo_pt: "Erro de Warmboot",
        alias: ["error warmboot", "crashea al despertar", "failed to mount warmboot", "pantalla negra suspension"],
        causas: ["Incompatibilidad de firmware al intentar despertar la consola. Suele pasar en consolas Mariko o al hacer downgrades (bajar de versión) sin quemar efuses, haciendo que el firmware del warmboot no coincida."],
        causas_en: ["Firmware incompatibility when waking up the console. Often happens on Mariko consoles or when downgrading without burning efuses, causing a warmboot mismatch."],
        causas_pt: ["Incompatibilidade de firmware ao tentar acordar o console. Geralmente ocorre em consoles Mariko ou ao fazer downgrades sem queimar efuses (incompatibilidade de warmboot)."],
        solucion: "Generalmente se soluciona asegurándote de usar la versión correcta de Hekate y Atmosphère para tu firmware, o reparando/reinstalando el firmware de la consola limpiamente mediante Daybreak.",
        solucion_en: "Usually fixed by ensuring you use the correct Hekate and Atmosphere version for your firmware, or cleanly repairing/reinstalling the firmware via Daybreak.",
        solucion_pt: "Geralmente é resolvido garantindo o uso da versão correta do Hekate e Atmosphère para seu firmware, ou reparando/reinstalando o firmware limpo via Daybreak.",
        fuente: "GitHub Issues (SciresM)"
    },
    {
        codigo: "Failed to init emuMMC",
        programa: "Hekate / emuMMC",
        titulo: "Fallo al iniciar la partición emuMMC",
        titulo_en: "Failed to initialize emuMMC partition",
        titulo_pt: "Falha ao iniciar partição emuMMC",
        alias: ["error emummc", "no encuentra emunand", "forced but not enabled", "pantalla roja hekate"],
        causas: ["La partición oculta de la emuNAND en la tarjeta SD se ha corrompido, tu SD está muriendo/es falsa, o has cambiado de tarjeta copiando y pegando mal (las particiones ocultas no se copian así)."],
        causas_en: ["Hidden emuNAND partition on SD card is corrupted, SD is dying/fake, or you cloned the SD card incorrectly (hidden partitions cannot be just copy-pasted)."],
        causas_pt: ["Partição oculta da emuNAND corrompida, o SD está morrendo/é falso, ou você clonou o SD incorretamente (partições ocultas não podem apenas ser copiadas/coladas)."],
        solucion: "1. Ve a Hekate -> emuMMC -> Migrate y fíjate si te la detecta para poder arreglarla.\\n2. Revisa que el archivo 'emummc/emummc.ini' apunte al sector correcto de tu SD.\\n3. Si la partición está corrupta sin arreglo, tendrás que extraer tus partidas guardadas (con software como NxNandManager en PC) y crear una emuMMC desde cero.",
        solucion_en: "1. Go to Hekate -> emuMMC -> Migrate to see if it detects it for a fix.\\n2. Check that 'emummc/emummc.ini' points to the correct SD sector.\\n3. If unrecoverably corrupted, extract your saves (e.g. NxNandManager on PC) and create a new emuMMC from scratch.",
        solucion_pt: "1. Vá em Hekate -> emuMMC -> Migrate e veja se detecta para reparo.\\n2. Verifique se 'emummc/emummc.ini' aponta para o setor SD correto.\\n3. Se estiver irremediavelmente corrompida, extraia seus saves (ex: NxNandManager) e crie uma nova emuMMC do zero.",
        fuente: "ElOtroLado / Scene"
    },
    {
        codigo: "No main boot entries found",
        programa: "Hekate (hekate_ipl.ini)",
        titulo: "Falta configuración de arranque (hekate_ipl.ini)",
        titulo_en: "Missing boot configuration (hekate_ipl.ini)",
        titulo_pt: "Falta configuração de inicialização (hekate_ipl.ini)",
        alias: ["error hekate_ipl", "no me salen los botones en hekate", "boot entries", "missing ipl"],
        causas: ["Hekate ha arrancado correctamente (el menú táctil), pero no sabe qué hacer porque le falta el archivo de texto que le dice dónde está y cómo cargar Atmosphère."],
        causas_en: ["Hekate booted correctly (touch menu), but it doesn't know what to do because it's missing the text file that tells it where and how to load Atmosphere."],
        causas_pt: ["Hekate iniciou corretamente (menu de toque), mas não sabe o que fazer porque falta o arquivo de texto que informa onde e como carregar o Atmosphère."],
        solucion: "Debes crear (o descargar de un pack confiable) un archivo llamado 'hekate_ipl.ini' y colocarlo dentro de la carpeta 'bootloader' de tu SD. Ese archivo contiene los botones que te aparecen en el menú 'Launch' para arrancar sysNAND o emuNAND.",
        solucion_en: "Create (or download from a trusted pack) a file named 'hekate_ipl.ini' and place it inside the 'bootloader' folder on your SD. This file contains the buttons in the 'Launch' menu.",
        solucion_pt: "Crie (ou baixe de um pack confiável) um arquivo 'hekate_ipl.ini' e coloque-o na pasta 'bootloader' do seu SD. Este arquivo contém os botões do menu 'Launch'.",
        fuente: "GitHub / GBATemp"
    },
    {
        codigo: "The software was closed",
        programa: "Horizon OS / Juegos",
        titulo: "Se ha cerrado el programa a causa de un error",
        titulo_en: "The software was closed because an error occurred",
        titulo_pt: "O software foi fechado porque ocorreu um erro",
        alias: ["se ha cerrado el programa", "juego se cierra solo", "software closed error", "error generico juego"],
        causas: ["Es el mensaje de error más genérico de Nintendo. Ocurre cuando un juego requiere un firmware mayor al que tienes, faltan sigpatches, hay un mod incompatible (ej. mods de Smash Bros o Zelda), o los datos del juego están corruptos."],
        causas_en: ["This is Nintendo's most generic error. Occurs when a game requires a higher firmware, missing sigpatches, incompatible mods (e.g., Smash/Zelda mods), or corrupted game data."],
        causas_pt: ["Este é o erro mais genérico da Nintendo. Ocorre quando um jogo requer um firmware maior, faltam sigpatches, mods incompatíveis (ex: Zelda/Smash mods) ou dados corrompidos."],
        solucion: "1. Actualiza tus parches de firmas (sigpatches).\\n2. Comprueba si el juego requiere un firmware de consola más alto del que tienes instalado.\\n3. Si tienes mods instalados (en 'atmosphere/contents/[TitleID]'), bórralos temporalmente para descartar conflictos.\\n4. Verifica datos corruptos desde las opciones de la consola.",
        solucion_en: "1. Update your signature patches (sigpatches).\\n2. Check if the game requires a higher firmware than your currently installed one.\\n3. If you have mods (in 'atmosphere/contents/[TitleID]'), delete them temporarily to rule out conflicts.\\n4. Check for corrupted data from the console options.",
        solucion_pt: "1. Atualize seus patches de assinatura (sigpatches).\\n2. Verifique se o jogo requer um firmware maior que o instalado.\\n3. Se tiver mods (em 'atmosphere/contents/[TitleID]'), apague-os temporariamente para descartar conflitos.\\n4. Verifique dados corrompidos nas opções do console.",
        fuente: "Nintendo / Comunidad"
    },
    {
        codigo: "2168-0002 (0x4a8)",
        programa: "0100000000000023 (AM)",
        titulo: "Crasheo del Application Manager",
        titulo_en: "Application Manager Crash",
        titulo_pt: "Crash do Application Manager",
        alias: ["error 0100000000000023", "0x4a8", "error al abrir juego sysmodule"],
        causas: ["El gestor de aplicaciones (Application Manager) de la consola se ha bloqueado. Casi siempre ocurre por culpa de un sysmodule en segundo plano que está desactualizado (como sys-clk, sys-botbase, SaltyNX, etc.) o un tema incompatible."],
        causas_en: ["The console's Application Manager has crashed. This is almost always caused by an outdated background sysmodule (like sys-clk, sys-botbase, SaltyNX, etc.) or an incompatible theme."],
        causas_pt: ["O Gerenciador de Aplicativos (Application Manager) travou. Quase sempre causado por um sysmodule em segundo plano desatualizado (como sys-clk, sys-botbase, SaltyNX) ou tema incompatível."],
        solucion: "1. Conecta tu tarjeta SD al PC y ve a la ruta 'atmosphere/contents/'.\\n2. Renombra la carpeta 'contents' a 'contents_bak' para desactivar todos los mods temporalmente.\\n3. Si la consola arranca y funciona bien, el problema era uno de esos sysmodules. Elimínalos o descárgalos actualizados para tu firmware.",
        solucion_en: "1. Connect SD card to PC and go to 'atmosphere/contents/'.\\n2. Rename the 'contents' folder to 'contents_bak' to disable all mods temporarily.\\n3. If the console boots fine, the issue was one of those sysmodules. Delete them or download updated versions.",
        solucion_pt: "1. Conecte o SD no PC e vá para 'atmosphere/contents/'.\\n2. Renomeie a pasta 'contents' para 'contents_bak' para desativar os mods temporariamente.\\n3. Se o console ligar normalmente, o problema era um desses sysmodules. Apague-os ou baixe versões atualizadas.",
        fuente: "GitHub Issues / Reddit"
    }
];
